name: Hello World！
spring:
  redis:
    host: 10.10.50.114
    port: 6379
    password: IyouquTest
    database: 0
    maxWaitMillis: 3000
    minEvictableIdleTimeMillis: 60000
    timeBetweenEvictionRunsMillis: 30000
    timeout: 5000
    usePool: true
    maxTotal: 500
    maxIdle: 200
    minIdle: 50